name: Test code and app
on:
  push:
#    paths:
#      - config.py
#      - src/**
#      - app/**
jobs:
  test_model:
    name: Test processed code and model
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Environment setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install linter
        run: pip install flake8

      - name: Run Linting
        run: flake8 src

      - name: Cache  # https://github.com/actions/cache/tree/v2
        # Allows caching dependencies and build outputs to improve workflow
        # execution time.
        uses: actions/cache@v2
        with:
          # List of files, directories, and wildcard patterns to cache and
          # restore
          path: ~/.cache/pip
          # An explicit key for restoring and saving the cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          #  An ordered list of keys to use for restoring the cache if no cache
          # hit occurred for key
          restore-keys: ${{ runner.os }}-pip-

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Test processed code and ML model
        run: |
          make test

      - name: Build and run app locally
        run: |
          docker build -t ci-cd-test . 
          docker run -p 3000:3000 -t ci-cd-test &
          sleep 10
          docker ps -q --filter ancestor="ci-cd-test" | xargs -r docker stop

      - name: Build and run app on Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_DEPLOYMENT}}
          heroku_app_name: "employee-predict-vantage-werne"
          heroku_email: "werner.van.der.veen@vantage-ai.com"
